{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.grigorenkomo",
    "module": "logging-starter",
    "version": "1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.1-SNAPSHOT.jar",
          "url": "logging-starter-1.1-SNAPSHOT.jar",
          "size": 1372,
          "sha512": "c3d6f0bdfb177d716db4cfee815e559d288460203acb481b46676ed774149d5d753cffc5933cd20bb88da74df0278d0e19901d8c337f2678359d4187fc9405d4",
          "sha256": "9ea91f87aa6aa39ec0ba5ca17f714b1ee9e15dbb55fefe72c8f06bd8e07b670d",
          "sha1": "fedd8be33983b04b174432a0bb495990ea6e0f07",
          "md5": "0731f5abfe36a4265cdc4aacbef5292c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-starter-1.1-SNAPSHOT.jar",
          "url": "logging-starter-1.1-SNAPSHOT.jar",
          "size": 1372,
          "sha512": "c3d6f0bdfb177d716db4cfee815e559d288460203acb481b46676ed774149d5d753cffc5933cd20bb88da74df0278d0e19901d8c337f2678359d4187fc9405d4",
          "sha256": "9ea91f87aa6aa39ec0ba5ca17f714b1ee9e15dbb55fefe72c8f06bd8e07b670d",
          "sha1": "fedd8be33983b04b174432a0bb495990ea6e0f07",
          "md5": "0731f5abfe36a4265cdc4aacbef5292c"
        }
      ]
    }
  ]
}
